-- Inventario Casa del Marqués — instalación PostgreSQL (vacía)
-- Prefijo: casa_marques_
-- Encoding: UTF8 (tildes y diéresis)
-- Zona horaria: America/Bogota
-- Datos iniciales: categoría General + usuario admin (clave 123456)
--
-- Uso (psql, conectado como superusuario o admin):
--   psql -U admin -d postgres -f database/install_postgres.sql
--
-- En servicios administrados (p. ej. Supabase) omita CREATE DATABASE
-- y ejecute desde SET TIME ZONE hasta el final sobre la base existente.

SET TIME ZONE 'America/Bogota';

SELECT 'CREATE DATABASE "Inventario_cm" WITH ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'Inventario_cm')\gexec

\connect "Inventario_cm"

SET TIME ZONE 'America/Bogota';
SET client_encoding = 'UTF8';

CREATE TABLE IF NOT EXISTS "casa_marques_Usuarios" (
    "Cedula" VARCHAR(20) NOT NULL PRIMARY KEY,
    "Nombres" VARCHAR(150) NOT NULL,
    "Password" VARCHAR(255) NOT NULL,
    "Tipo" VARCHAR(20) NOT NULL DEFAULT 'Usuario' CHECK ("Tipo" IN ('Admin', 'Usuario')),
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo'))
);

CREATE TABLE IF NOT EXISTS "casa_marques_Categorias" (
    "id_categoria" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(100) NOT NULL,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo', 'Eliminado'))
);

CREATE TABLE IF NOT EXISTS "casa_marques_Inventario" (
    "Codigo" VARCHAR(50) NOT NULL PRIMARY KEY,
    "Elemento" VARCHAR(150) NOT NULL,
    "id_categoria" INTEGER DEFAULT NULL,
    "Descripcion" TEXT,
    "Cantidad" INTEGER NOT NULL DEFAULT 0,
    "Fotografia" VARCHAR(255) DEFAULT NULL,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo', 'Eliminado')),
    CONSTRAINT fk_casa_marques_inv_categoria
        FOREIGN KEY ("id_categoria")
        REFERENCES "casa_marques_Categorias" ("id_categoria") ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "casa_marques_Movimientos" (
    "id_movimiento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Tipo" VARCHAR(20) NOT NULL CHECK ("Tipo" IN ('Ingreso', 'Prestamo', 'Devolucion', 'Dar_Baja')),
    "Consecutivo" INTEGER NOT NULL,
    "Fecha" DATE NOT NULL,
    "Cedula_cuentadante" VARCHAR(20) DEFAULT NULL,
    "Descripcion" TEXT,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo', 'Cerrado')),
    "id_movimiento_ref" INTEGER DEFAULT NULL,
    CONSTRAINT fk_casa_marques_mov_cuentadante
        FOREIGN KEY ("Cedula_cuentadante")
        REFERENCES "casa_marques_Usuarios" ("Cedula") ON UPDATE CASCADE,
    CONSTRAINT fk_casa_marques_mov_ref
        FOREIGN KEY ("id_movimiento_ref")
        REFERENCES "casa_marques_Movimientos" ("id_movimiento") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "casa_marques_Det_Movimientos" (
    "Consecutivo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_movimiento" INTEGER NOT NULL,
    "id_Detalle" INTEGER NOT NULL DEFAULT 1,
    "Codigo_elemento" VARCHAR(50) NOT NULL,
    "Cantidad" INTEGER NOT NULL DEFAULT 1,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo')),
    CONSTRAINT fk_casa_marques_det_movimiento
        FOREIGN KEY ("id_movimiento")
        REFERENCES "casa_marques_Movimientos" ("id_movimiento") ON DELETE CASCADE,
    CONSTRAINT fk_casa_marques_det_inventario
        FOREIGN KEY ("Codigo_elemento")
        REFERENCES "casa_marques_Inventario" ("Codigo") ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "casa_marques_Movimiento_Fotos" (
    "id_foto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_movimiento" INTEGER NOT NULL,
    "Ruta" VARCHAR(255) NOT NULL,
    "Orden" SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT fk_casa_marques_foto_movimiento
        FOREIGN KEY ("id_movimiento")
        REFERENCES "casa_marques_Movimientos" ("id_movimiento") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "casa_marques_Solicitudes_Prestamo" (
    "id_solicitud" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Cedula_solicitante" VARCHAR(20) NOT NULL,
    "Fecha_solicitud" DATE NOT NULL,
    "Descripcion" TEXT,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'Pendiente'
        CHECK ("Estado" IN ('Pendiente', 'Aprobada', 'Rechazada', 'Cancelada')),
    "id_movimiento" INTEGER DEFAULT NULL,
    "Cedula_aprobador" VARCHAR(20) DEFAULT NULL,
    "Fecha_resolucion" TIMESTAMP DEFAULT NULL,
    "Motivo_rechazo" TEXT DEFAULT NULL,
    CONSTRAINT fk_casa_marques_sol_solicitante
        FOREIGN KEY ("Cedula_solicitante")
        REFERENCES "casa_marques_Usuarios" ("Cedula") ON UPDATE CASCADE,
    CONSTRAINT fk_casa_marques_sol_movimiento
        FOREIGN KEY ("id_movimiento")
        REFERENCES "casa_marques_Movimientos" ("id_movimiento") ON DELETE SET NULL,
    CONSTRAINT fk_casa_marques_sol_aprobador
        FOREIGN KEY ("Cedula_aprobador")
        REFERENCES "casa_marques_Usuarios" ("Cedula") ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "casa_marques_Det_Solicitudes" (
    "id_detalle" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_solicitud" INTEGER NOT NULL,
    "id_linea" INTEGER NOT NULL DEFAULT 1,
    "Codigo_elemento" VARCHAR(50) NOT NULL,
    "Cantidad" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_casa_marques_detsol_solicitud
        FOREIGN KEY ("id_solicitud")
        REFERENCES "casa_marques_Solicitudes_Prestamo" ("id_solicitud") ON DELETE CASCADE,
    CONSTRAINT fk_casa_marques_detsol_inventario
        FOREIGN KEY ("Codigo_elemento")
        REFERENCES "casa_marques_Inventario" ("Codigo") ON UPDATE CASCADE
);

INSERT INTO "casa_marques_Categorias" ("Nombre", "Estado")
SELECT 'General', 'Activo'
WHERE NOT EXISTS (
    SELECT 1 FROM "casa_marques_Categorias" WHERE "Nombre" = 'General'
);

INSERT INTO "casa_marques_Usuarios" ("Cedula", "Nombres", "Password", "Tipo", "Estado")
SELECT 'admin', 'Administrador Sistema',
       '$2y$10$zIA6XnjeLRv5noLtmWP4zuOIrUSpbB27eVRGVcMhyrGaBnT6iH8nO',
       'Admin', 'Activo'
WHERE NOT EXISTS (
    SELECT 1 FROM "casa_marques_Usuarios" WHERE "Cedula" = 'admin'
);
-- Contraseña del admin: 123456
