-- Inventario Casa del Marqués — esquema PostgreSQL para Supabase
-- Datos iniciales: categoría General (No Consumible) + usuario admin (clave 123456)
--
-- Tablas a instalar (prefijo + nombre):
--   1. {prefijo}Usuarios
--   2. {prefijo}Categorias
--   3. {prefijo}Inventario
--   4. {prefijo}Movimientos
--   5. {prefijo}Det_Movimientos
--   6. {prefijo}Movimiento_Fotos
--   7. {prefijo}Solicitudes_Prestamo
--   8. {prefijo}Det_Solicitudes
--
-- Uso en Supabase SQL Editor:
--   1. Edite solo la variable prefijo (debe coincidir con DB_PREFIX en .env)
--   2. Ejecute todo el script
--
-- Uso por CLI (toma el prefijo de .env):
--   php database/install_supabase.php

SET TIME ZONE 'America/Bogota';
SET client_encoding = 'UTF8';
SET search_path TO public;

DO $install$
DECLARE
    -- Único valor a cambiar. Si omite el _ final, se agrega solo.
    prefijo text := 'casa_marques_';
    p text;
BEGIN
    p := trim(prefijo);
    IF p <> '' AND right(p, 1) <> '_' THEN
        p := p || '_';
    END IF;

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "Cedula" VARCHAR(20) NOT NULL PRIMARY KEY,
            "Nombres" VARCHAR(150) NOT NULL,
            "Password" VARCHAR(255) NOT NULL,
            "Tipo" VARCHAR(20) NOT NULL DEFAULT 'Usuario' CHECK ("Tipo" IN ('Admin', 'Usuario')),
            "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo'))
        )
    $sql$, p || 'Usuarios');

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "id_categoria" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Nombre" VARCHAR(100) NOT NULL,
            "Indicador" VARCHAR(20) DEFAULT NULL,
            "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo', 'Eliminado'))
        )
    $sql$, p || 'Categorias');

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "Codigo" VARCHAR(50) NOT NULL PRIMARY KEY,
            "Elemento" VARCHAR(150) NOT NULL,
            "id_categoria" INTEGER DEFAULT NULL,
            "Descripcion" TEXT,
            "Cantidad" INTEGER NOT NULL DEFAULT 0,
            "Fotografia" VARCHAR(255) DEFAULT NULL,
            "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo', 'Eliminado'))
        )
    $sql$, p || 'Inventario');

    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Inventario',
        'fk_' || rtrim(p, '_') || '_inv_categoria'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("id_categoria") REFERENCES %I ("id_categoria") ON UPDATE CASCADE',
        p || 'Inventario',
        'fk_' || rtrim(p, '_') || '_inv_categoria',
        p || 'Categorias'
    );

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "id_movimiento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Tipo" VARCHAR(20) NOT NULL CHECK ("Tipo" IN ('Ingreso', 'Prestamo', 'Devolucion', 'Dar_Baja', 'Consumo')),
            "Consecutivo" INTEGER NOT NULL,
            "Fecha" DATE NOT NULL,
            "Cedula_cuentadante" VARCHAR(20) DEFAULT NULL,
            "Descripcion" TEXT,
            "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo', 'Cerrado')),
            "id_movimiento_ref" INTEGER DEFAULT NULL
        )
    $sql$, p || 'Movimientos');

    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Movimientos',
        'fk_' || rtrim(p, '_') || '_mov_cuentadante'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("Cedula_cuentadante") REFERENCES %I ("Cedula") ON UPDATE CASCADE',
        p || 'Movimientos',
        'fk_' || rtrim(p, '_') || '_mov_cuentadante',
        p || 'Usuarios'
    );
    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Movimientos',
        'fk_' || rtrim(p, '_') || '_mov_ref'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("id_movimiento_ref") REFERENCES %I ("id_movimiento") ON DELETE SET NULL',
        p || 'Movimientos',
        'fk_' || rtrim(p, '_') || '_mov_ref',
        p || 'Movimientos'
    );

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "Consecutivo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "id_movimiento" INTEGER NOT NULL,
            "id_Detalle" INTEGER NOT NULL DEFAULT 1,
            "Codigo_elemento" VARCHAR(50) NOT NULL,
            "Cantidad" INTEGER NOT NULL DEFAULT 1,
            "Estado" VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK ("Estado" IN ('Activo', 'Inactivo'))
        )
    $sql$, p || 'Det_Movimientos');

    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Det_Movimientos',
        'fk_' || rtrim(p, '_') || '_det_movimiento'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("id_movimiento") REFERENCES %I ("id_movimiento") ON DELETE CASCADE',
        p || 'Det_Movimientos',
        'fk_' || rtrim(p, '_') || '_det_movimiento',
        p || 'Movimientos'
    );
    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Det_Movimientos',
        'fk_' || rtrim(p, '_') || '_det_inventario'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("Codigo_elemento") REFERENCES %I ("Codigo") ON UPDATE CASCADE',
        p || 'Det_Movimientos',
        'fk_' || rtrim(p, '_') || '_det_inventario',
        p || 'Inventario'
    );

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "id_foto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "id_movimiento" INTEGER NOT NULL,
            "Ruta" VARCHAR(255) NOT NULL,
            "Orden" SMALLINT NOT NULL DEFAULT 1
        )
    $sql$, p || 'Movimiento_Fotos');

    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Movimiento_Fotos',
        'fk_' || rtrim(p, '_') || '_foto_movimiento'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("id_movimiento") REFERENCES %I ("id_movimiento") ON DELETE CASCADE',
        p || 'Movimiento_Fotos',
        'fk_' || rtrim(p, '_') || '_foto_movimiento',
        p || 'Movimientos'
    );

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "id_solicitud" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Cedula_solicitante" VARCHAR(20) NOT NULL,
            "Fecha_solicitud" DATE NOT NULL,
            "Descripcion" TEXT,
            "Estado" VARCHAR(20) NOT NULL DEFAULT 'Pendiente'
                CHECK ("Estado" IN ('Pendiente', 'Aprobada', 'Rechazada', 'Cancelada')),
            "id_movimiento" INTEGER DEFAULT NULL,
            "Cedula_aprobador" VARCHAR(20) DEFAULT NULL,
            "Fecha_resolucion" TIMESTAMP DEFAULT NULL,
            "Motivo_rechazo" TEXT DEFAULT NULL
        )
    $sql$, p || 'Solicitudes_Prestamo');

    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Solicitudes_Prestamo',
        'fk_' || rtrim(p, '_') || '_sol_solicitante'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("Cedula_solicitante") REFERENCES %I ("Cedula") ON UPDATE CASCADE',
        p || 'Solicitudes_Prestamo',
        'fk_' || rtrim(p, '_') || '_sol_solicitante',
        p || 'Usuarios'
    );
    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Solicitudes_Prestamo',
        'fk_' || rtrim(p, '_') || '_sol_movimiento'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("id_movimiento") REFERENCES %I ("id_movimiento") ON DELETE SET NULL',
        p || 'Solicitudes_Prestamo',
        'fk_' || rtrim(p, '_') || '_sol_movimiento',
        p || 'Movimientos'
    );
    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Solicitudes_Prestamo',
        'fk_' || rtrim(p, '_') || '_sol_aprobador'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("Cedula_aprobador") REFERENCES %I ("Cedula") ON UPDATE CASCADE',
        p || 'Solicitudes_Prestamo',
        'fk_' || rtrim(p, '_') || '_sol_aprobador',
        p || 'Usuarios'
    );

    EXECUTE format($sql$
        CREATE TABLE IF NOT EXISTS %I (
            "id_detalle" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "id_solicitud" INTEGER NOT NULL,
            "id_linea" INTEGER NOT NULL DEFAULT 1,
            "Codigo_elemento" VARCHAR(50) NOT NULL,
            "Cantidad" INTEGER NOT NULL DEFAULT 1
        )
    $sql$, p || 'Det_Solicitudes');

    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Det_Solicitudes',
        'fk_' || rtrim(p, '_') || '_detsol_solicitud'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("id_solicitud") REFERENCES %I ("id_solicitud") ON DELETE CASCADE',
        p || 'Det_Solicitudes',
        'fk_' || rtrim(p, '_') || '_detsol_solicitud',
        p || 'Solicitudes_Prestamo'
    );
    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p || 'Det_Solicitudes',
        'fk_' || rtrim(p, '_') || '_detsol_inventario'
    );
    EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("Codigo_elemento") REFERENCES %I ("Codigo") ON UPDATE CASCADE',
        p || 'Det_Solicitudes',
        'fk_' || rtrim(p, '_') || '_detsol_inventario',
        p || 'Inventario'
    );

    EXECUTE format(
        'INSERT INTO %I ("Nombre", "Indicador", "Estado")
         SELECT %L, %L, %L
         WHERE NOT EXISTS (SELECT 1 FROM %I WHERE "Nombre" = %L)',
        p || 'Categorias',
        'General',
        'No Consumible',
        'Activo',
        p || 'Categorias',
        'General'
    );

    EXECUTE format(
        'INSERT INTO %I ("Cedula", "Nombres", "Password", "Tipo", "Estado")
         SELECT %L, %L, %L, %L, %L
         WHERE NOT EXISTS (SELECT 1 FROM %I WHERE "Cedula" = %L)',
        p || 'Usuarios',
        'admin',
        'Administrador Sistema',
        '$2y$10$zIA6XnjeLRv5noLtmWP4zuOIrUSpbB27eVRGVcMhyrGaBnT6iH8nO',
        'Admin',
        'Activo',
        p || 'Usuarios',
        'admin'
    );
END
$install$;
-- Contraseña del admin: 123456
